# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    #runs-on: ubuntu-latest
    #runs-on: windows-latest
    runs-on: windows-2019

    steps:

    - name: Install SQL Server
      uses: Particular/install-sql-server-action@v1.0.0
      with:
        connection-string-env-var: SQL_SERVER_CONNECTION_STRING
        catalog: Audit
        
    - name: Create SQL tables
      shell: pwsh
      run: |
          echo "Create additional tables $SQL_SERVER_CONNECTION_STRING"
          sqlcmd -Q "CREATE TABLE [Event] ( EventId BIGINT IDENTITY(1,1) NOT NULL, InsertedDate datetimeoffset NOT NULL DEFAULT(GETDATE()), LastUpdatedDate datetimeoffset NOT NULL DEFAULT(GETDATE()), EventType NVARCHAR(MAX), [Data] NVARCHAR(MAX) NOT NULL, CONSTRAINT PK_Event PRIMARY KEY (EventId) )" -d "Audit" -I
          sqlcmd -Q "CREATE VIEW dbo.[v_Event] WITH SCHEMABINDING AS SELECT EventId, InsertedDate, LastUpdatedDate, CAST(JSON_VALUE(Data, '$.EventType') AS NVARCHAR(255)) AS [EventType], CAST(JSON_VALUE(Data, '$.ReferenceId') AS NVARCHAR(255)) AS [ReferenceId], JSON_VALUE(Data, '$.Environment.Exception') As [Exception], JSON_VALUE(Data, '$.Environment.MachineName') AS [MachineName], CAST(JSON_VALUE(Data, '$.Environment.UserName') AS NVARCHAR(50)) AS [UserName], JSON_VALUE(Data, '$.Environment.CallingMethodName') AS [CallingMethodName], CAST(JSON_VALUE(Data, '$.StartDate') AS NVARCHAR(35)) AS [CreatedDate], CAST(JSON_VALUE(Data, '$.EndDate') AS NVARCHAR(35)) As [CommitDate], CAST(JSON_VALUE(Data, '$.Duration') AS INT) As [Duration], JSON_VALUE(Data, '$.Target.Type') As [TargetType], COALESCE(JSON_VALUE(Data, '$.Target.Old'), JSON_QUERY(Data, '$.Target.Old')) AS [TargetOld], COALESCE(JSON_VALUE(Data, '$.Target.New'), JSON_QUERY(Data, '$.Target.New')) AS [TargetNew], JSON_QUERY(Data, '$.Comments') AS [Comments], [Data] As [Data] FROM dbo.[Event]" -d "Audit" -I
          sqlcmd -Q "CREATE UNIQUE CLUSTERED INDEX PK_V_EVENT ON [v_Event] (EventId)" -d "Audit" -I
          sqlcmd -Q "CREATE INDEX IX_V_EVENT_EventType_ReferenceId ON [v_Event] (EventType, ReferenceId)" -d "Audit" -I
          sqlcmd -Q "CREATE INDEX IX_V_EVENT_CreatedDate ON [v_Event] (CreatedDate)" -d "Audit" -I
          sqlcmd -Q "CREATE INDEX IX_V_EVENT_CommitDate ON [v_Event] (CommitDate)" -d "Audit" -I
          

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          1.0.4
          2.1.x
          3.1.x
          5.0.x
          6.0.x
          7.0.x          
          
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'      
      with:
        nuget-version: '6.x'      
        
      
    - name: Nuget Restore
      run: nuget restore Audit.NET.sln
      
    - name: Dotnet Restore 
      run: dotnet restore
      
    - name: MsBuild Audit.EntityFramework.UnitTest
      run: |
        msbuild.exe .\test\Audit.EntityFramework.UnitTest -p:Configuration=Release

    - name: Dotnet Build Audit.NET.sln
      run: dotnet build .\Audit.NET.sln --no-restore --configuration release
      
    - name: Test Audit.Mvc.UnitTest
      run: dotnet test .\test\Audit.Mvc.UnitTest --no-build --configuration release --verbosity normal

    - name: Test Audit.JsonAdapter.UnitTest
      run: dotnet test .\test\Audit.JsonAdapter.UnitTest --no-build --configuration release --verbosity normal
      
    - name: Test Audit.WebApi.UnitTest
      run: dotnet test .\test\Audit.WebApi.UnitTest --no-build --configuration release --verbosity normal
      
    - name: Test Audit.DynamicProxy.UnitTest
      run: dotnet test .\test\Audit.DynamicProxy.UnitTest --no-build --configuration release --verbosity normal
     
    - name: Test Audit.Wcf.UnitTest
      run: dotnet test .\test\Audit.Wcf.UnitTest --no-build --configuration release --verbosity normal
      
    - name: Test Audit.UnitTest
      run: dotnet test .\test\Audit.UnitTest --no-build --configuration release --verbosity normal
      
    - name: Test Audit.EntityFramework.Core.UnitTest
      run: dotnet test .\test\Audit.EntityFramework.Core.UnitTest --no-build --configuration release --verbosity normal

    - name: Test Audit.EntityFramework.Core.v3.UnitTest
      run: dotnet test .\test\Audit.EntityFramework.Core.v3.UnitTest --no-build --configuration release --verbosity normal

    - name: Test Audit.EntityFramework.Full.UnitTest
      run: dotnet test .\test\Audit.EntityFramework.Full.UnitTest --no-build --configuration release --verbosity normal
      
